#!/usr/bin/env python3
"""Generate the speeder riding phenotypes: animation banks, body roots and robes.

A mounted rider switches to a riding phenotype (22 for normal bodies, 24 for
large bodies). Body parts fall back to the base phenotype through
phenotype.2da DefaultPhenoType, but three kinds of model must exist per riding
phenotype:

* an animation bank that replaces locomotion and idle clips with the seated
  pose and inherits every other clip from the ordinary bank;
* a body root for each race and gender whose supermodel is that bank;
* a copy of every robe whose supermodel is the riding root or bank. A robe
  animates through its own supermodel chain, so the base-phenotype robe would
  keep standing and running while the body sits.

Robes are byte copies of their base-phenotype twins with only names changed, so
animation part IDs, skin bindings and tint materials are preserved. The riding
models keep the complete skeleton of the model they replace because the
compiler matches part IDs against the immediate parent's tree only.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import shutil
import struct
import subprocess
import sys
import time

import CompileModels as mdl
import GenerateTintMapAssets as tint
import RobeAnimations as anim

ROOT = Path(__file__).resolve().parents[1]
POSE = json.loads((ROOT / "tools" / "SpeederRiderPose.json").read_text(encoding="utf8"))
BANK_DIRECTORY = ROOT / "sw_cr_creature"
ROOT_DIRECTORY = ROOT / "sw_pt_root"
ROBE_DIRECTORY = ROOT / "sw_pt_robe"
STOCK_ROBES = ROOT / "tools" / "SpeederRiderStockRobes.json"
HEADER = "# SWLOR speeder rider model generated by tools/GenerateSpeederRiderModels.py\n"
# Base phenotype -> riding phenotype. Keep in step with phenotype.2da and SpeederItemDefinition.
PHENOTYPES = {"0": "22", "2": "24"}
# Animation banks used directly by robes or body roots, and their riding replacements.
BANKS = {
    "a_ba": "a_ba_rd", "a_fa": "a_fa_rd", "a_da": "a_da_rd", "a_dfa": "a_dfa_rd",
    "a_ba2": "a_ba2_rd", "a_fa2": "a_fa2_rd", "a_da2": "a_da2_rd", "a_dfa2": "a_dfa2_rd",
    "a_ba_coat": "a_ba_coat_rd", "a_fa_coat": "a_fa_coat_rd", "a_da_coat": "a_da_coat_rd",
    "a_dfa_coat": "a_dfa_coat_rd", "a_fa_skirt": "a_fa_skirt_rd", "a_ba_non_combat": "a_ba_noncmb_rd",
    "hss_pmh0": "hss_pmh0_rd", "hss_pfh0": "hss_pfh0_rd",
}
FEMALE_BANKS = {"a_fa", "a_dfa", "a_fa2", "a_dfa2", "a_fa_coat", "a_dfa_coat", "a_fa_skirt", "hss_pfh0"}
REFERENCE_BANK = {"male": "a_ba", "female": "a_fa"}
# Clips a mounted character can reach. Everything else is inherited unchanged.
FULL_BODY_CLIPS = (
    "pause1", "pause2", "pausebrd", "pausepsn", "pausesh", "pausetrd", "pauseturn", "plpause1",
    "pausewalkl", "pausewalkr", "pausewalkfl", "pausewalkfr", "walk", "run", "runfl", "runfr",
    "walkinj", "walkdead", "cwalkf", "cwalkb", "cwalkl", "cwalkr", "cturnr",
    "1hreadyl", "1hreadyr", "2hreadyl", "2hreadyr", "2wreadyl", "2wreadyr", "nwreadyl", "nwreadyr",
    "plreadyl", "plreadyr", "tlknorm", "tlkplead", "tlkforce", "tlklaugh", "listen", "hturnl", "hturnr",
    "getmid", "getmidlp", "getlow", "getlowlp",
)
# Carry overlays animate one arm while the body runs; keep both hands on the controls instead.
OVERLAY_CLIPS = {
    "walk_swordr": "rbicep_g", "run_swordr": "rbicep_g", "walk_swordl": "lbicep_g", "run_swordl": "lbicep_g",
    "walk_bowl": "lbicep_g", "run_bowl": "lbicep_g", "walk_shieldl": "lbicep_g", "run_shieldl": "lbicep_g",
}
CLIPS = {**{clip: "rootdummy" for clip in FULL_BODY_CLIPS}, **OVERLAY_CLIPS}
ROBE = re.compile(r"^(p[mf][a-z])([02])_robe(\d+)$")
BODY = re.compile(r"^(p[mf][a-z])([02])$")


def number(value):
    return format(value, ".7g")


def riding_name(name):
    """Riding replacement for a robe's or root's supermodel; None keeps the original."""
    body = BODY.match(name)
    if body:
        return body[1] + PHENOTYPES[body[2]]
    return BANKS.get(name)


def bank_source(name, parent, text):
    """Animation-only model holding the seated clips over the parent's complete skeleton."""
    gender = "female" if parent in FEMALE_BANKS else "male"
    pose = POSE[gender]
    nodes = {name: {"parent": ["null"]}, **anim.skeleton(text, [], name)}
    ordered = anim.order_nodes(nodes, name)
    if any(bone not in nodes for bone in ("rootdummy", "torso_g", "pelvis_g")):
        raise ValueError(f"{parent}: not a humanoid body skeleton")
    keys = {}
    # Garment banks carry partial skeletons; a robe only binds to the bones its bank has.
    garment = POSE["garment"]
    rotations = {**pose["bones"], **garment["rotations"],
                 **{panel: pose["bones"][bone] for panel, bone in garment["follow"].items()}}
    for bone, rotation in rotations.items():
        if bone not in nodes:
            continue
        row = [number(value) for value in rotation]
        keys[bone] = {"orientationkey": [["0", *row], ["1", *row]]}
    return nodes, ordered, keys, pose


def bank_model(name, parent, text, reference_height):
    nodes, ordered, keys, pose = bank_source(name, parent, text)
    bind = [float(value) for value in nodes["rootdummy"].get("position", ["0", "0", "0"])]
    # Seat height follows the skeleton's own leg length; each wearer's animation scale applies on top.
    height = pose["root"][2] * bind[2] / reference_height
    row = [number(pose["root"][0]), number(pose["root"][1]), number(height)]
    keys["rootdummy"] = {"positionkey": [["0", *row], ["1", *row]]}
    output = (HEADER + f"newmodel {name}\nsetsupermodel {name} {parent}\nclassification CHARACTER\n"
              f"setanimationscale 1\nbeginmodelgeom {name}\n" +
              "".join(anim.serialize_node(node, props) for node, props in ordered) + f"endmodelgeom {name}\n")
    for clip, animation_root in CLIPS.items():
        if animation_root not in nodes:
            continue
        clip_nodes = "".join(anim.serialize_node(node, {"parent": props["parent"], **keys.get(node, {})})
                             for node, props in ordered)
        output += (f"newanim {clip} {name}\n  length 1\n  transtime 0.25\n  animroot {animation_root}\n"
                   f"{clip_nodes}doneanim {clip} {name}\n")
    return (output + f"donemodel {name}\n").encode("latin1")


def level_tail(text, gender):
    """Cancel the seated pelvis tilt on the tail attachment so the bike stays level.

    The bike is a tail model hanging off the pelvis. The tail attachment has no
    animation part ID in the body skeletons, so clips cannot key it; the riding
    root's bind pose carries the correction instead.
    """
    axis = POSE[gender]["bones"]["pelvis_g"]
    rotation = " ".join(number(value) for value in (*axis[:3], -axis[3]))
    def replace(match):
        block = re.sub(r"(?im)^\s*orientation\s.*\n", "", match[0])
        return re.sub(r"(?im)^(\s*parent\s.*\n)", rf"\g<1>  orientation {rotation}\n", block, count=1)
    result, count = re.subn(r"(?ims)^\s*node\s+\S+\s+tail\s*$.*?^\s*endnode\b", replace, text)
    if count != 1:
        raise ValueError("Body root must have exactly one tail attachment")
    return result


def root_model(name, base_name, text, parent):
    """The base body root under a new name, animated by the riding bank."""
    # Race-specific clips stay with the base root; the riding bank supplies the mounted ones.
    body = text.split("newanim", 1)[0] if re.search(r"(?im)^\s*newanim\b", text) else text
    body = level_tail(body, "female" if name[1] == "f" else "male")
    body = re.sub(rf"(?i)(?<![\w.]){re.escape(base_name)}(?![\w.])", name, body)
    body, count = re.subn(r"(?im)^(\s*setsupermodel\s+\S+\s+)\S+", rf"\g<1>{parent}", body)
    if count != 1:
        raise ValueError(f"{base_name}: expected one supermodel declaration")
    if not re.search(r"(?im)^\s*donemodel\b", body):
        body = body.rstrip() + f"\ndonemodel {name}\n"
    return (HEADER + body).encode("latin1")


def inherited_parts(name, load):
    """Animation part ID of every node path, taken from the nearest compiled ancestor that has it."""
    result = {}
    seen = set()
    while name and name not in seen:
        seen.add(name)
        data = load(name)
        if data is None:
            break
        if mdl.binary(data):
            for path, part in anim.binary_parts(data).items():
                if part >= 0:
                    result.setdefault(path, part)
        name = mdl.supermodel(data)
    return result


def match_inherited_parts(compiled, load):
    """Number a riding root's joints the way the clips above its bank expect.

    The compiler matches part IDs against the immediate parent only. The
    short-legged banks lack cloak and belt joints, so those received fresh IDs
    and the clips inherited from further up the chain would stop reaching them.
    """
    result = bytearray(compiled)
    expected = inherited_parts(mdl.supermodel(compiled), load)
    uint = lambda offset: struct.unpack_from("<I", compiled, offset)[0]
    def visit(pointer, path):
        offset = pointer + 12
        current = (*path, fixed(compiled, offset + 32, 32)) if path is not None else ()
        if current in expected:
            struct.pack_into("<i", result, offset + 28, expected[current])
        for index in range(uint(offset + 76)):
            visit(uint(12 + uint(offset + 72) + index * 4), current)
    visit(uint(84), None)
    anim.validate_animation_parts(bytes(result))
    return bytes(result)


def fixed(data, offset, size):
    return data[offset:offset + size].split(b"\0", 1)[0].decode("ascii").lower()


def rename_binary(data, old, new, parent, disabled_clips):
    """Copy a compiled robe under a new model name and supermodel, changing nothing else."""
    result = bytearray(data)
    uint = lambda offset: struct.unpack_from("<I", data, offset)[0]
    def put(offset, size, value):
        encoded = value.encode("ascii")
        if len(encoded) >= size:
            raise ValueError(f"{value}: name exceeds the {size}-byte field")
        result[offset:offset + size] = encoded.ljust(size, b"\0")
    def visit(pointer):
        node = 12 + pointer
        if fixed(data, node + 32, 32) == old:
            put(node + 32, 32, new)
        for index in range(uint(node + 76)):
            visit(uint(12 + uint(node + 72) + index * 4))
    # Some legacy robes were copied between styles without renaming their internal
    # model. Keep that mismatch: tint binding addresses the subtree by file name.
    internal = fixed(data, 20, 64)
    if internal != old:
        old, new = internal, (robe_copy_name(internal) if ROBE.match(internal) else internal)
    put(20, 64, new)
    put(180, 64, parent)
    visit(uint(84))
    for index in range(uint(136)):
        animation = 12 + uint(12 + uint(132) + index * 4)
        clip = fixed(data, animation + 8, 64)
        if clip in disabled_clips:
            # A robe's private copy of a locomotion clip would override the seated pose.
            put(animation + 8, 64, ("x" + clip)[:63])
        if fixed(data, animation + 120, 64) == old:
            put(animation + 120, 64, new)
        visit(uint(animation + 72))
    return bytes(result)


def rename_ascii(data, old, new, parent, disabled_clips):
    text = data.decode("latin1")
    text = re.sub(rf"(?i)(?<![\w.]){re.escape(old)}(?![\w.])", new, text)
    text = re.sub(r"(?im)^(\s*setsupermodel\s+\S+\s+)\S+", rf"\g<1>{parent}", text, count=1)
    for clip in disabled_clips:
        text = re.sub(rf"(?im)^(\s*(?:newanim|doneanim)\s+){re.escape(clip)}(\s)", rf"\g<1>x{clip}\2", text)
    return text.encode("latin1")


def robe_copy_name(name):
    match = ROBE.match(name)
    return f"{match[1]}{PHENOTYPES[match[2]]}_robe{match[3]}"


def robe_copy(name, data):
    new = robe_copy_name(name)
    parent = mdl.supermodel(data)
    target = riding_name(parent) or parent
    rename = rename_binary if mdl.binary(data) else rename_ascii
    return new, rename(data, name, new, target, set(CLIPS))


class Decompiler:
    def __init__(self, stage):
        self.stage = stage
        for folder in ("binary", "decompiled"):
            (stage / folder).mkdir(parents=True, exist_ok=True)
        self.compiler, _ = mdl.prepare_compiler(stage)

    def text(self, name, data):
        if not mdl.binary(data):
            return data.decode("latin1")
        (self.stage / "binary" / f"{name}.mdl").write_bytes(data)
        mdl.run_compiler(self.compiler, self.stage, ["-d", str(self.stage / "binary" / f"{name}.mdl"),
                                                     str(self.stage / "decompiled" / f"{name}.mdl")], f"{name}.log")
        return (self.stage / "decompiled" / f"{name}.mdl").read_text(encoding="latin1")


def plan(game_data, stage, force=False):
    """Every generated resource as {path: bytes}, plus the ASCII models that need compiling."""
    active = tint.find_active_models()
    stock = tint.read_stock_key_models(game_data)
    decompiler = Decompiler(stage)
    def load(name):
        if name in active:
            return active[name].read_bytes()
        if name in stock:
            return tint.extract_stock_bif_resource(*stock[name])
        return None
    sources, robes, stock_robes = {}, {}, []
    heights = {}
    for gender, reference in REFERENCE_BANK.items():
        nodes = anim.skeleton(decompiler.text(reference, load(reference)), [], "reference")
        heights[gender] = float(nodes["rootdummy"]["position"][2])
    for parent, name in BANKS.items():
        data = load(parent)
        if data is None:
            raise RuntimeError(f"Animation bank {parent} is absent from the HAK sources and the installed game")
        gender = "female" if parent in FEMALE_BANKS else "male"
        sources[BANK_DIRECTORY / f"{name}.mdl"] = bank_model(name, parent, decompiler.text(parent, data), heights[gender])
    for base_name in sorted(name for name in {*active, *stock} if BODY.match(name)):
        data = load(base_name)
        parent = mdl.supermodel(data)
        if parent not in BANKS:
            raise RuntimeError(f"{base_name}: no riding bank for supermodel {parent}")
        name = riding_name(base_name)
        sources[ROOT_DIRECTORY / f"{name}.mdl"] = root_model(name, base_name, decompiler.text(base_name, data), BANKS[parent])
    for base_name in sorted(name for name in {*active, *stock} if ROBE.match(name)):
        name, data = robe_copy(base_name, load(base_name))
        if base_name not in active and (ROBE_DIRECTORY / f"{name}.mdl").is_file() and not force:
            # A stock robe gets its tint materials bound after it is copied
            # (GenerateTintMapAssets.py --import-stock-models); do not unbind it.
            stock_robes.append(base_name)
            continue
        # Tint binding addresses nodes by compiled offsets, so ASCII robes are compiled like the banks.
        (robes if mdl.binary(data) else sources)[ROBE_DIRECTORY / f"{name}.mdl"] = data
        if base_name not in active:
            stock_robes.append(base_name)
    return sources, robes, stock_robes


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-data", type=Path, required=True, help="Installed EE data directory, for stock roots, banks and robes")
    parser.add_argument("--force", action="store_true", help="Also rewrite robes copied from the installed game, discarding their tint bindings")
    parser.add_argument("--apply", action="store_true", help="Write the generated models and compile the ASCII ones in place")
    args = parser.parse_args()
    stage = ROOT / "output" / f"speeder-rider-{time.time_ns()}"
    sources, robes, stock_robes = plan(args.game_data, stage, args.force)
    riding = re.compile(rf"^p[mf][a-z](?:{'|'.join(PHENOTYPES.values())})_robe\d+\.mdl$")
    kept = {robe_copy_name(name) for name in stock_robes}
    stale = sorted(path.name for path in ROBE_DIRECTORY.iterdir()
                   if riding.match(path.name) and path not in robes and path not in sources and path.stem not in kept)
    changed = [path for path, data in robes.items() if not path.is_file() or path.read_bytes() != data]
    print(f"{len(sources)} compiled banks, body roots and ASCII robes; {len(robes)} copied robes ({len(changed)} changed, {len(stale)} stale).")
    if not args.apply:
        return
    for name in stale:
        (ROBE_DIRECTORY / name).unlink()
    for path in changed:
        path.write_bytes(robes[path])
    for path, data in sources.items():
        path.write_bytes(data)
    # Base robes that exist only in the installed game, so audits can run without it.
    STOCK_ROBES.write_text(json.dumps(stock_robes, indent=2) + "\n", encoding="utf8", newline="\n")
    command = [sys.executable, "-B", str(ROOT / "tools" / "CompileModels.py"), "--game-data", str(args.game_data), "--apply"]
    for path in sources:
        command += ["--model", path.stem]
    subprocess.run(command, cwd=ROOT, check=True)
    active = tint.find_active_models()
    stock = tint.read_stock_key_models(args.game_data)
    def load(name):
        if name in active:
            return active[name].read_bytes()
        return tint.extract_stock_bif_resource(*stock[name]) if name in stock else None
    for path in sources:
        if path.parent == ROOT_DIRECTORY:
            path.write_bytes(match_inherited_parts(path.read_bytes(), load))
    shutil.rmtree(stage, ignore_errors=True)


if __name__ == "__main__":
    main()
